# Generated by Django 4.2.2 on 2023-06-21 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='online_library.profile'),
            preserve_default=False,
        ),
    ]
