# Generated by Django 4.2.2 on 2023-06-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        ('album_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='prince',
            new_name='price',
        ),
        migrations.AddField(
            model_name='album',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profile_app.profile'),
            preserve_default=False,
        ),
    ]
