# Generated by Django 4.2.1 on 2023-05-17 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_hour',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
