# Generated by Django 4.2.1 on 2023-05-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_task_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_url',
            field=models.URLField(default='https://www.google.com'),
        ),
    ]
