# Generated by Django 4.2.1 on 2023-05-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_task_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_email',
        ),
    ]
