# Generated by Django 4.2.1 on 2023-05-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_task_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
