# Generated by Django 4.2.1 on 2023-05-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_task_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
